site_name: Alok Knowledgebase
theme:
  name: material
  features:
    - navigation.tabs # Optional: adds top-level tabs
    - navigation.sections # Groups left nav items
    - toc.integrate # Integrates the right TOC
plugins:
  - search
  - tags
