site_name: Alok Knowledgebase
theme:
  name: material
  features:
    - navigation.tabs # Optional: adds top-level tabs
    - navigation.sections # Groups left nav items
    - toc.integrate # Integrates the right TOC
plugins:
  - search
  - tags


nav:
  - Home: index.md
  - Analytics: data_science.md
    - Descriptive: anlytics/descriptive.md
    - Inferential: anlytics/inferential.md
  - Artifical Intelligence: ai.md
  - Marketing Science: marketing_science.md
